[node]
installers = "dnf,apt,apk,yum"
name = "NodeJS"
description = "NodeJs v12"

[kubectl]
installers = "apt,yum,curl"
name = "Kubectl"
description = "kubectl controls the Kubernetes cluster manager"

[git]
installers = "apt,yum,pacman,dnf,apk"
name = "Git"
description = "Git SVM"

[pip3]
installers = "dnf,pacman,apt,apk,yum"
name = "Pip3"
description = "Pip is the package installer for Python"

[gcloud]
installers = "curl"
name = "gCloud"
description = "CLI tool of GCP"

[nginx]
installers = "dnf,pacman,apt,apk,yum"
name = "Nginx"
description = "Nginx server"

[hlf]
installers = "curl"
name = "Fabric"
description = "Hyperledger Fabric"

[docker]
installers = "apt,yum"
name = "Docker"
description = "Docker"

[eksctl]
installers = "curl"
name = "eksctl"
description = "A simple CLI tool for creating clusters on EKS"

[ctop]
installers = "curl"
name = "cTop"
description = "Top-like interface for container metrics"

[hello]
installers = "apt,yum,pacman,apk,dnf,curl"
name = "Hello"
description = "This is just a sample tool"

[python3]
installers = "apt,yum,pacman,apk,dnf"
name = "Python 3"
description = "Python 3"
