[node]
installers = "apt,yum,dnf,apk"
name = "NodeJS"

[git]
installers = "apt,yum,pacman,dnf,apk"
name = "Git"
description = "Git SVM"

[gcloud]
installers = "curl"
name = "gCloud"
description = "CLI tool of GCP"

[nginx]
installers = "apt,yum,pacman,apk,dnf"
name = "Nginx"
description = "Nginx server"

[hlf]
installers = "curl"
name = "Fabric"
description = "Hyperledger Fabric"

[docker]
installers = "apt,yum"
name = "Docker"
description = "Docker"

[hello]
installers = "apt,yum,pacman,apk,dnf,curl"
name = "Hello"
description = "This is just a sample tool"

[python3]
installers = "apt,yum,pacman,apk,dnf"
name = "Python 3"
description = "Python 3"
