name = "Docker Compose"
shortname = "docker-compose"
description = "Docker Compose is a tool for defining and running multi-container Docker applications"
issue = ""

[curl]
sh = """
@sudo curl -L "https://github.com/docker/compose/releases/download/1.26.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
@sudo chmod +x /usr/local/bin/docker-compose
"""
