name = "Git"
shortname = "git"
description = "Git SVM"
issue = "https://github.com/leopardslab/installer.to/issues/1"

[apt]
sh = """
@sudo apt-get update
@sudo apt-get install git
"""

[yum]
sh = """
@sudo yum install git
"""

[pacman]
sh = """
pacman -Sy git
"""

[dnf]
sh = """
@sudo dnf install git
"""

[apk]
sh = """
@sudo apk add git
"""
