name = "Atom"
shortname = "atom"
description = "A hackable text editor for the 21st Century"
issues = "https://github.com/leopardslab/installer.to/issues/35"

[apt]
sh = """
wget -qO - https://packagecloud.io/AtomEditor/atom/gpgkey | @sudo apt-key add -
@sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list'
@sudo apt-get update
@sudo apt-get install atom
"""

[yum]
sh = """
@sudo rpm --import https://packagecloud.io/AtomEditor/atom/gpgkey
@sudo sh -c 'echo -e "[Atom]\nname=Atom Editor\nbaseurl=https://packagecloud.io/AtomEditor/atom/el/7/\$basearch\nenabled=1\ngpgcheck=0\nrepo_gpgcheck=1\ngpgkey=https://packagecloud.io/AtomEditor/atom/gpgkey" > /etc/yum.repos.d/atom.repo'
@sudo dnf install atom
"""

[pacman]
sh = """
@sudo pacman -S atom
"""

[apk]
sh = """
@sudo apk add atom
"""

[dnf]
sh = """
@sudo rpm --import https://packagecloud.io/AtomEditor/atom/gpgkey
@sudo sh -c 'echo -e "[Atom]\nname=Atom Editor\nbaseurl=https://packagecloud.io/AtomEditor/atom/el/7/\$basearch\nenabled=1\ngpgcheck=0\nrepo_gpgcheck=1\ngpgkey=https://packagecloud.io/AtomEditor/atom/gpgkey" > /etc/yum.repos.d/atom.repo'
@sudo dnf install atom
"""
