[apt]
sh = """
echo "Installing hello"
echo "Installed hello"
"""

[yum]
sh = """
echo "Installing hello"
echo "Installed hello"
"""


[apk]
sh = """
echo "Installing hello"
echo "Installed hello"
"""
