name = "NodeJS"
shortname = "node"
description = "NodeJs v12"

[apt]
sh = """
curl -sL https://deb.nodesource.com/setup_12.x | @sudo -E bash -
@sudo apt-get install -y nodejs
"""

[yum]
sh = """
@sudo yum install nodejs12
"""

[dnf]
sh = """
@sudo dnf install -y gcc-c++ make
curl -sL https://rpm.nodesource.com/setup_12.x | @sudo -E bash -
@sudo dnf install nodejs
"""

[apk]
sh = """
@sudo apk update
@sudo apk add nodejs
"""
