name = "Fabric"
shortname = "hlf"
description = "Hyperledger Fabric"


[apt]
sh = """
@sudo apt-get update
@sudo apt-get install git
"""

[yum]
sh = """
@sudo yum install git
"""

[pacman]
sh = """
pacman -Sy git
"""

[dnf]
sh = """
@sudo dnf install git
"""

[apk]
sh = """
@sudo apk add git
"""
