name = "Fabric"
shortname = "hlf"
description = "Hyperledger Fabric"


[curl]
sh = """
if ! command -v docker
then
    @warn "Docker could not be found"
    curl https://installer.to/docker | bash
else
    @info "Docker found"
fi

@info "Downloading Fabric........"
curl -sSL http://bit.ly/2ysbOFE -o bootstrap.sh
chmod 755 ./bootstrap.sh
@sudo bash ./bootstrap.sh

@sudo cp ./fabric-samples/bin/*    /usr/local/bin
"""
