[apt]
sh = """
sudo apt-get update
sudo apt-get install nginx
"""

[yum]
sh = """
sudo yum install nginx
"""

[pacman]
sh = """
@sudo pacman -S nginx
"""

[apk]
sh = """
sudo apk update
sudo apk add nginx
"""

[dnf]
sh = """
sudo dnf install nginx
"""
