name = "Nginx"
shortname = "nginx"
description = "Nginx server"
issues = "https://github.com/leopardslab/installer.to/issues/3"

[apt]
sh = """
@sudo apt-get update
@sudo apt-get install nginx
"""

[yum]
sh = """
@sudo yum install nginx
"""

[pacman]
sh = """
@sudo pacman -S nginx
"""

[apk]
sh = """
@sudo apk update
@sudo apk add nginx
"""

[dnf]
sh = """
@sudo dnf install nginx
"""
