name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Get the list of modified installers only
        uses: technote-space/get-diff-action@v1
        with:
          PREFIX_FILTER: |
            installers/
      - name: Generate installers, update README.md & installers.toml
        if: env.GIT_DIFF
        run: ./generate.sh ${{ env.GIT_DIFF }}
      - name: Minify generated installers
        if: env.GIT_DIFF
        run: ./minify.sh ${{ env.GIT_DIFF }}
      - name: Find the Related PR
        if: env.GIT_DIFF
        uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Related PR
        if:  env.GIT_DIFF && success() && steps.findPr.outputs.number
        id: vars
        run: |
          echo "The related PR is ${PR}"
          echo ::set-output name=pr_id::"${PR}"
        env:
          PR: ${{ steps.findPr.outputs.pr }}
      - name: Create a pull request for README.md & installers.toml updates
        if: env.GIT_DIFF
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update installer scripts, README.md & installers.toml
          title: Update installer scripts, README.md & installers.toml for #${{ steps.vars.outputs.pr_id }}
          body: |
            Updated installer scripts, `README.md` & `installers.toml` according to the changes done in the `installer.toml`s.
            This is a automatically generated PR in related to PR #${{ steps.vars.outputs.pr_id }}
          branch: update-readme-md-and-installers-toml-${{ steps.vars.outputs.pr_id }}
          labels: automated-pr, continious-delivery
      - name: Archive Production Artifact
        if: env.GIT_DIFF
        uses: actions/upload-artifact@master
        with:
          name: installers
          path: installers

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Get the list of modified installers only
        uses: technote-space/get-diff-action@v1
        with:
          PREFIX_FILTER: |
            installers/
      - name: Download Artifact
        if: env.GIT_DIFF
        uses: actions/download-artifact@master
        with:
          name: installers
          path: installers
      - name: Install Dependencies
        run: cd functions && npm install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --project installer-to
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to Google Cloud Bucket
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: installer-to
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: rsync -r installers gs://installer-to.appspot.com/
          cli: gsutil
