name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test-alpine:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Tests on Alpine Linux
      run: docker run alpine pwd
      
  test-ubuntu:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Tests on Ubuntu Linux
      run: docker run ubuntu pwd
      
  test-git:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get the list of modified files only
      run: git diff --name-status HEAD master | awk '{if ($1 == "M") print $2}' 
