name: Run tests

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:

  test-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v1
      - name: Run tests for the modified/ added files
        run: |
          pip install toml pytablewriter
          python generate.py ${{ env.GIT_DIFF }}
          docker build -t shellspec .
          docker run -v $PWD:/app shellspec bash -c "cd /app && ./test.sh ${{ env.GIT_DIFF }}"
