name: Run tests

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:

  test-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v1
      - name: Run tests for the modified/ added files
        run: |
          pip install toml pytablewriter
          python generate.py ${{ env.GIT_DIFF }}
          echo ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u ${{ github.actor }} --password-stdin
          docker run -v $PWD:/app docker.pkg.github.com/${{ github.repository }}/shellspec:apt bash -c "cd /app && ./test.sh ${{ env.GIT_DIFF }}"
